In [57]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import time 
from tensorflow.keras.models import Sequential, load_model
from keras.layers import SimpleRNN, Dense
import tensorflow as tf
import array

In [67]:
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = np.array([1,1,1,1,1,0,0,0,0,0])

In [68]:
labels

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [61]:
# integer encode the documents
vocab_size = 50
encoded_docs = [tf.keras.preprocessing.text.one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[27, 20], [5, 44], [41, 41], [9, 44], [16], [15], [9, 41], [16, 5], [9, 44], [48, 44, 20, 34]]


In [62]:
# pad documents to a max length of 4 words
max_length = 4
padded_docs = tf.keras.preprocessing.sequence.pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[27 20  0  0]
 [ 5 44  0  0]
 [41 41  0  0]
 [ 9 44  0  0]
 [16  0  0  0]
 [15  0  0  0]
 [ 9 41  0  0]
 [16  5  0  0]
 [ 9 44  0  0]
 [48 44 20 34]]


In [69]:
padded_docs = np.array(padded_docs)
padded_docs

array([[27, 20,  0,  0],
       [ 5, 44,  0,  0],
       [41, 41,  0,  0],
       [ 9, 44,  0,  0],
       [16,  0,  0,  0],
       [15,  0,  0,  0],
       [ 9, 41,  0,  0],
       [16,  5,  0,  0],
       [ 9, 44,  0,  0],
       [48, 44, 20, 34]], dtype=int32)

In [70]:
# define the model
model = Sequential()
model.add(tf.keras.layers.Embedding(vocab_size, 8, input_length=max_length))
model.add(tf.keras.layers.Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_8 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_6 (Flatten)          (None, 32)                0         
_________________________________________________________________
module_wrapper_6 (ModuleWrap (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [73]:
# fit the model
history = model.fit(padded_docs, labels, epochs=50, verbose=0)

In [74]:
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 89.999998
